site_url: https://weinmacher-nick.netlify.app/
logo_url: https://weinmacher-nick.netlify.app/icon.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  repo: markus-ebner/weinmacher-nick
  squash_merges: true

media_folder: static/img
public_folder: /img

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [de, nl]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: de

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: "Site settings"
    name: "site"
    files:
      - label: "Info"
        name: "info"
        file: "content/site/info.json"
        format: "json"
        editor:
          preview: false
        fields:
          - {
              label: Site Name,
              name: sitename,
              widget: string,
              hint: "This is used for the site title",
            }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: "This is used as descriptive text for links that link to this site",
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern:
                [
                  "^[a-z]{2}([-])?([A-Za-z]{2})?$",
                  'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")',
                ],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # editor:
    #   preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "projects"
    i18n: true
    label: "Projects"
    label_singular: "Project"
    folder: "content/projects"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    preview_path: "projects/{{slug}}"
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          i18n: true,
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
          required: false,
        }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
          i18n: true,
          allow_multiple: false,
        }
      - {
          label: "Content",
          name: "body",
          widget: "markdown",
          i18n: true,
          required: false,
        }
      - {
          i18n: true,
          label: "Gallery",
          name: "gallery",
          widget: "list",
          required: false,
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image" },
        }
  - name: "about"
    i18n: true
    label: "About us"
    label_singular: "About us"
    folder: "content/about"
    format: "frontmatter"
    slug: "about"
    preview_path: "about"
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        i18n: true,
        required: true,
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        i18n: true,
        required: false,
      }
      - {
        label: "Cover Image",
        name: "cover",
        widget: "image",
        required: false,
        i18n: true,
        allow_multiple: false,
      }
      - {
        label: "Content",
        name: "body",
        widget: "markdown",
        i18n: true,
        required: false,
      }
